// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `img_proc_server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package imgprocserver;

public interface ImgProcServerInterface extends Ice.Object,
                                                _ImgProcServerInterfaceOperations, _ImgProcServerInterfaceOperationsNC
{
    public static final long serialVersionUID = -9097725192772270629L;
}
