// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `img_proc_server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package imgprocserver;

public final class ImgProcServerInterfaceHolder extends Ice.ObjectHolderBase<ImgProcServerInterface>
{
    public
    ImgProcServerInterfaceHolder()
    {
    }

    public
    ImgProcServerInterfaceHolder(ImgProcServerInterface value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof ImgProcServerInterface)
        {
            value = (ImgProcServerInterface)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _ImgProcServerInterfaceDisp.ice_staticId();
    }
}
